spring.application.name=business

spring.datasource.url=${POSTGRES_DB_URL_SEVENCOWS}
spring.datasource.username=${POSTGRES_DB_USER_SEVENCOWS}
spring.datasource.password=${POSTGRES_DB_PASSWORD_SEVENCOWS}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect